## Education

**Northwestern University** [Class of 2018]{style="float:right"}  
Master of Science - Data Science (Formerly Predictive Analytics)

**California State University, Fullerton** [Class of 2011]{style="float:right"}  
Master of Business Administration - Finance  

**Hawai'i Pacific University** [Class of 2008]{style="float:right"}  
Bachelor of Science in Business Administration - Finance  

## Professional Experience

**Ramsey Solutions** [2025-Present]{style="float:right"}  
Senior Analytics Engineer  

**Sabbatical** [2022-2025]{style="float:right"}  
Father & Husband  

**AllianceBernstein L.P.** [2022-2022]{style="float:right"}  
Vice President - Data Analytics Lead  

**Pacific Investment Management Company** [2014-2022]{style="float:right"}  
Specialist - Equity, ETF, Derivative & Fixed Income Pricing  
Senior Associate - Equity, ETF, Derivative & Fixed Income Pricing  

**Fidelity Management & Research Company** [2013-2014]{style="float:right"}  
Senior Investment Data Analyst  

**TD Ameritrade Inc.** [2011-2013]{style="float:right"}  
Process Management & Automation Analyst  
Brokerage Operations Leadership Development Rotation Analyst  

## Core Business & Technical Competencies

<!--
**Leadership & Strategy:**

  - [Placeholder]

**Operations Management:**

  - [Placeholder]
-->

**Data Engineering:** 
 
  - Data Orchestration (Airflow & Dagster)
  - Data Integration (Fivetran & AWS Glue)

**Analytics Engineering:**

  - Data Transformation (dbt)
  - Data Modeling

**Data Analysis:**

  - Exploratory Data Analysis
  - Storytelling with Data
  - Data Wrangling
  - Statistical Analysis

**Data Product & Visualization:**

  - Interactive Dashboards (Streamlit, Dash, Shiny, and Quarto)
  - Business Intelligence (Tableau, Microsoft Power BI, and MicroStrategy)

**Database Management:**

  - Amazon Redshift & S3
  - Oracle SQL Developer
  - Microsoft SQL Server
  - Snowflake

**Enterprise Systems:**

  - Salesforce CRM
  - Oracle NetSuite
  - Bloomberg Terminal

**Project Management:**

  - Project Management Software (Atlassian JIRA)
  - Master Data Management
  - Agile & Kanban

**Process Management**

  - Process Improvement
  - Process Automation
  - Standard Operating Procedures

**Computer Programming:**

  - Python
  - SQL
  - VBA
  - HTML
  - CSS
 